# Generated by Django 4.1.7 on 2023-03-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='retailers',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.DeleteModel(
            name='Retailer',
        ),
    ]
