# Generated by Django 4.1.7 on 2023-03-25 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiHuge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='common_names',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='scientific_name',
        ),
    ]
