# Generated by Django 4.1.7 on 2023-03-27 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writtenId', models.CharField(default='0000', max_length=30, verbose_name='Written ID')),
                ('name', models.CharField(max_length=30)),
                ('condition', models.TextField(blank=True, max_length=100, null=True)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('checked_out_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_to', to=settings.AUTH_USER_MODEL)),
                ('librarian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='librarian', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writtenId', models.CharField(help_text='<i>The number written on item</i>', max_length=30, unique=True, verbose_name='Written ID')),
                ('name', models.CharField(help_text='<i>e.g. cordless drill 3</i>', max_length=30)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('condition', models.TextField(blank=True, help_text='Update changes upon return if necessary', max_length=100, null=True)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('m', 'Maintenance'), ('o', 'On loan'), ('r', 'Reserved')], default='a', help_text='Item availability', max_length=1)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shareshack.department')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_back'],
                'permissions': (('can_mark_returned', 'Can checkout and return items'), ('donation_intake', 'Process new donations')),
            },
        ),
    ]
